version: '3.8'
services:
  jenkins:
    build: ./jenkins_with_dotnet/
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home_1:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_home_1: {}